/**
 * @file editor_config.h
 **/

#ifndef _FLUX_EDITOR_CONFIG_
#define _FLUX_EDITOR_CONFIG_

#define EDITOR_VERSION_STRING "flux-editor-v0.0.0"

#define EDITOR_TEXT_INPUT_MAX_CHARS 500
#define EDITOR_PANEL_MAX_TEXT_INPUT_BOXES 100
#define EDITOR_CONSOLE_STACK_SIZE 100
#define EDITOR_CONSOLE_COMMAND_MAX_NAME 500
#define EDITOR_CONSOLE_MAX_COMMANDS 500

#define LOG_FLUX_EDITOR 13
#define LOG_FLUX_EDITOR_WARNING 14
#define LOG_FLUX_EDITOR_ERROR 15

#endif