#ifndef _FLUX_EDITOR_CONFIG_
#define _FLUX_EDITOR_CONFIG_

#define EDITOR_VERSION_STRING "flux-editor-v0.0.0"

#define EDITOR_TEXT_INPUT_MAX_CHARS 500
#define EDITOR_PANEL_MAX_TEXT_INPUT_BOXES 50
#define EDITOR_CONSOLE_STACK_SIZE 100

#endif